import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import NavBar, { NavLink } from "@/components/navbar/NavBar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap", // Optional, adds font-display: swap;
});

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StoreProvider>
        <NavBar>
          <NavLink href="/admin/dashboard">Dashboard</NavLink>
          <NavLink href="/admin/categories">Categories</NavLink>
          <NavLink href="/admin/products">Products</NavLink>
          <NavLink href="/admin/orders">Orders</NavLink>
          <NavLink href="/admin/users">Users</NavLink>
        </NavBar>
        <main className="mx-5">{children}</main>
      </StoreProvider>
    </>
  );
}
