import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import NavBar, { NavLink } from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap", // Optional, adds font-display: swap;
});

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StoreProvider>
      <NavBar>
          <NavLink href="/">Home</NavLink>
          <NavLink href="/categories">Categories</NavLink>
          <NavLink href="/about">About us</NavLink>
        </NavBar>
        <main className="mx-5">{children}</main>
        <Footer />
      </StoreProvider>
    </>
  );
}
